export const MEDIUM_BUTTONS = [
    'bold'
    , 'italic'
    , 'underline'

    , 'subscript'
    , 'superscript'
    , 'anchor'
    , 'quote'
    , 'pre'
    , 'orderedlist'
    , 'unorderedlist'
    , 'indent'
    , 'justifyLeft'
    , 'justifyCenter'
    , 'justifyRight'
    , 'justifyFull'
    , 'h1'
    , 'h2'
    , 'h3'
    , 'h4'
    , 'h5'
    , 'h'
];
